# Generated by Django 5.2.17 on 2026-09-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='Бренд')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Цена (сум)')),
                ('image', models.ImageField(blank=True, help_text='Загрузите фотографию через Admin. Если фото нет — на сайте будет показан placeholder.', null=True, upload_to='products/', verbose_name='Фотография')),
                ('category', models.CharField(blank=True, choices=[('edp', 'Eau de Parfum'), ('edt', 'Eau de Toilette'), ('parfum', 'Parfum'), ('edc', 'Eau de Cologne'), ('niche', 'Нишевая парфюмерия'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('volume', models.CharField(blank=True, help_text='Например: 100 ml', max_length=30, verbose_name='Объём')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('unisex', 'Унисекс')], default='unisex', max_length=10, verbose_name='Пол')),
                ('top_notes', models.CharField(blank=True, max_length=255, verbose_name='Верхние ноты')),
                ('middle_notes', models.CharField(blank=True, max_length=255, verbose_name='Средние ноты')),
                ('base_notes', models.CharField(blank=True, max_length=255, verbose_name='Базовые ноты')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Парфюм',
                'verbose_name_plural': 'Парфюмы',
                'ordering': ['-created_at'],
            },
        ),
    ]
